name: build and push with workload identity federation
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildAndPush:
    name: build and push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT_NAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.GAR_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Push
        uses: docker/build-push-action@v4
        with:
          tags: ${{ vars.GAR_REGISTRY }}/petclinic-workload-identity-federation:latest
          push: true

